<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Test"
           tests="1"
           failures="1"
           errors="0"
           skipped="0"
           time="3.786">
  <properties />
            <testcase name="logindata" time="3.786" classname="org.abc.tt.Fetchdata">
                <failure type="java.lang.AssertionError"
                  message="expected [Login &amp; Signup Form] but found [Facebook - log in or sign up]"
              >
<![CDATA[java.lang.AssertionError: expected [Login & Signup Form] but found [Facebook - log in or sign up]
  org.testng.Assert.fail(Assert.java:99)
  org.testng.Assert.failNotEquals(Assert.java:1037)
  org.testng.Assert.assertEqualsImpl(Assert.java:140)
  org.testng.Assert.assertEquals(Assert.java:122)
  org.testng.Assert.assertEquals(Assert.java:629)
  org.testng.Assert.assertEquals(Assert.java:639)
  org.abc.tt.Fetchdata.logindata(Fetchdata.java:34)
  java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  java.base/java.lang.reflect.Method.invoke(Method.java:580)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
  org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
  org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
  org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
  org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
  org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
  java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
  org.testng.TestRunner.privateRun(TestRunner.java:794)
  org.testng.TestRunner.run(TestRunner.java:596)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
  org.testng.SuiteRunner.run(SuiteRunner.java:276)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
  org.testng.TestNG.runSuites(TestNG.java:1063)
  org.testng.TestNG.run(TestNG.java:1031)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
      </failure>

          </testcase>
  
  
  
</testsuite>
